### ISSUE TITLE
StreamingIngestionSample fails to populate timestamp field in adx table

### ISSUE THREAD

**Issue by kiranpradeep** [Azure/azure-kusto-samples-dotnet#5]
StreamingIngestionSample works correctly without any changes. Then I minimally modified the StreamingIngestSample by replacing `DateTime.Now` (line [193](https://github.com/Azure/azure-kusto-samples-dotnet/blob/0484ef7ffe943342ecd6611aa710fd7cb729afe1/client/StreamingIngestionSample/Program.cs#L193)) with `new DateTime(1970, 1, 12)`. The sample still works correctly.

But, if I replace`DateTime.Now` with `new DateTime(1970, 1, 13)`, a new row is created as expected, but the _timestamp_ field is empty. It appear the date is getting treated as month at some place.

I use netCore and nuget version 8.1.5. But, there is no other change I have made to the sample.

**Comment by yihezkel** [comment]
We apologize for not responding much earlier.
Since this was from 2020, it's no wonder the code you ran was from 2019.

I tested it using the latest code, and could not reproduce your issue. Specifically, line 201 (what used to be line 193):
`tw.WriteLine("{0},{1},{2},{3}", new DateTime(1970, 1, 13), i, "Sample event text ddddddddddddd", "\"{'Prop1':1, 'Prop2': 'Text'}\"");`
resulted in:
<img width="438" alt="image" src="https://github.com/Azure/azure-kusto-samples-dotnet/assets/30245027/78e8f54b-da06-4554-8cb5-61303bd6d15a">
